name: EzQuran Landing Page Deployment

on:
  push:
    branches:
      - main  # or your chosen branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22  # or the version you use

      - name: Install Dependencies
        run: |
          yarn install
          # or npm ci

      - name: Build For Development
        run: |
          yarn build:dev

      - name: Deploy to Remote Server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          source: "dist/*"
          target: "/home/ezquran/website/staging"
          strip_components: 1

      - name: Build For Staging
        run: |
          yarn build:staging

      - name: Deploy to Remote Server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          source: "dist/*"
          target: "/home/ezquran/website/staging"
          strip_components: 1

      - name: Build For Production
        run: |
          yarn build:production

      - name: Deploy to Remote Server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          source: "dist/*"
          target: "/home/ezquran/website/production"
          strip_components: 1
